name: NoBG
slug: nobg
version: "1.0.10"
description: Remove image backgrounds
url: https://github.com/doodles172/nobg

arch:
  - amd64
  - aarch64

startup: application
boot: auto

ports:
  3000/tcp: 3000

ports_description:
  3000/tcp: NoBG web interface

options: {}
schema: {}