name: NoBG
slug: nobg
version: "1.0.6"
description: Remove image backgrounds
url: https://github.com/doodles172/nobg

arch:
  - amd64
  - aarch64

build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest

startup: application
boot: auto

ingress: true
ingress_port: 3000

panel_icon: mdi:image-remove
panel_title: NoBG

ports:
  3000/tcp: 3000

ports_description:
  3000/tcp: NoBG web interface

options: {}
schema: {}